# Numpy Surgery

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


One Dimension

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(f"Dimension: {arr1.ndim}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")
print(f"Size: {arr1.size}")

Dimension: 1
Shape: (5,)
Data type: int64
Size: 5


Two Dimension

In [ ]:
import numpy as np
lst = [1,2,3,4,5]
arr1 = np.array([
                 [1,2,3,4,5,6]
                 ])
print(f"Dimension: {arr1.ndim}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")
print(f"Size: {arr1.size}")


Dimension: 2
Shape: (1, 6)
Data type: int64
Size: 6


Three Dimension

In [ ]:
import numpy as np
lst = [1,2,3,4,5]
arr1 = np.array([
                 [1,2,3,4,5],
                 [1,2,3,4,5]
                 ])
print(f"Dimension: {arr1.ndim}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")
print(f"Size: {arr1.size}")


Dimension: 2
Shape: (2, 5)
Data type: int64
Size: 10


Four Dimension

In [ ]:
import numpy as np
lst = [1,2,3,4,5]
arr1 = np.array(
    [
        [
            [1,2,3,4,5],
            [1,2,3,4,5]
        ],
        [
            [1,2,3,4,5],
            [1,2,3,4,5]
        ],
        [
            [1,2,3,4,5],
            [1,2,3,4,5]
        ],
    ]
)
print(f"Dimension: {arr1.ndim}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")
print(f"Size: {arr1.size}")


Dimension: 3
Shape: (3, 2, 5)
Data type: int64
Size: 30


In [ ]:
import numpy as np
lst = [1,2,3,4,5]
arr1 = np.array(
    [
        [
            [
                [1,2,3,4,5]
            ]
        ]
    ]
)
print(f"Dimension: {arr1.ndim}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")
print(f"Size: {arr1.size}")


Dimension: 4
Shape: (1, 1, 1, 5)
Data type: int64
Size: 5


Upcasting - convert data type a mutual data type in which all will fit

In [29]:
import numpy as np
arr1 = np.array([1,2,3,4,5.5])
print(arr1.dtype)


float64


In [30]:
import numpy as np
arr1 = np.array([1,2,3,4,'shakib'])
print(arr1.dtype)


<U21


In [38]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1.dtype)


int64


In [37]:
import numpy as np
arr1 = np.array([1,2,3,4],dtype=np.int8)
print(arr1.dtype)

int8


In [39]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1.dtype)
arr1 = arr1.astype(np.int8)
print(arr1.dtype)


int64
int8


# Nd Array From Existing Data

From List

In [53]:
import numpy as np
lst = [1,2,3,4,5]
arr = np.array(lst, dtype=np.int64)

print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


From Tuple

In [ ]:
import numpy as np
tpl = (1,2,3,4,5)
arr = np.array(tpl)

print(arr)
print(type(arr))
print(arr.dtype)

[ 5 10 15 20 25]
<class 'numpy.ndarray'>
int64


In [63]:
import numpy as np
st = {1,2,3,4,5}
arr = np.array(list(st))

print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


From Dictionary

In [70]:
import numpy as np
dct = {'name':'shakib','age':26}
values = dct.values()
keys = dct.keys()
items = dct.items()
print(values)
print(keys)
print(items)
arr = np.array(list(dct))

print(arr)
print(type(arr))
print(arr.dtype)

dict_values(['shakib', 26])
dict_keys(['name', 'age'])
dict_items([('name', 'shakib'), ('age', 26)])
['name' 'age']
<class 'numpy.ndarray'>
<U4


# Nd Array From Scratch

In [ ]:
# zeros - zeros_like

import numpy as np
arr = np.zeros(5)
# print(arr)
arr1 = np.zeros((5))
# print(arr1)
arr2 = np.zeros((5,2))
# print(arr2)
arr3 = np.zeros((5,3,2))
# print(arr3)


old_array = [
    [
        [1,2,3],
        [1,2,3],
        [1,2,3],
    ]
]
arr4 = np.zeros_like(old_array)
print(arr4)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [118]:
# ones - ones_like

import numpy as np
arr = np.ones(5)
# print(arr)
arr1 = np.ones((5))
# print(arr1)
arr2 = np.ones((5,2))
# print(arr2)
arr3 = np.ones((5,3,2))
print(arr3)


old_array = [
    [
        [1,2,3],
        [1,2,3],
        [1,2,3],
    ]
]
arr4 = np.ones_like(old_array)
# print(arr4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [123]:
# empty - empty_like

import numpy as np
arr = np.empty(5)
print(arr)
arr1 = np.empty((5))
# print(arr1)
arr2 = np.empty((5,2))
# print(arr2)
arr3 = np.empty((5,3,2))
# print(arr3)


old_array = [
    [
        [1,2,3],
        [1,2,3],
        [1,2,3],
    ]
]
arr4 = np.empty_like(old_array)
# print(arr4)

[1. 1. 1. 1. 1.]


In [134]:
# full - full_like

import numpy as np
arr = np.full(5,1)
# print(arr)
arr1 = np.full((5,1),5)
# print(arr1)
arr2 = np.full((5,2),4)
# print(arr2)
arr3 = np.full((5,3,2),9)
# print(arr3)


old_array = [
    [
        [1,2,3],
        [1,2,3],
        [1,2,3],
    ]
]
arr4 = np.full_like(old_array,78)
print(arr4)

[[[78 78 78]
  [78 78 78]
  [78 78 78]]]


# Nd Array With Random Values

In [45]:
import numpy as np
# np.random.rand(size)
arr = np.random.rand(5)
# print(arr)
arr1 = np.random.rand(2,3)
# print(arr1)

# np.random.randint(start, end, size)
arr2 = np.random.randint(100,size=(15))
# print(arr2)
arr3 = np.random.randint(100, size=(2,3,4))
# print(arr3)

# select a random number from lst
arr4 = np.random.choice([1,2,3,4], size=(2,3))
# print(arr4)
arr5 = np.random.choice([1,2,3,4], size=(2,3))
# print(arr5)


random.rand, random.randint(startNumber, endNumber, shape), random.uniform(startNumber, endNumber, shape), 

# Create An Array With Function

In [108]:
import numpy as np
# np.arange(start, end, step)
arr = np.arange(0, 50, 5)
# print(arr)

arr1,step = np.linspace(1, 10, 5, retstep=True)
# print(arr1,step)

arr2 = np.linspace(1, 20, 4).reshape(2,2)
# print(arr2)

# numpy.logspace(start,stop,num = 50,endpoint = True,base = 10.0,dtype = None)
arr3 = np.logspace(1,5,10).reshape(5,2)
# print(arr3)

# Matrix Creation

In [ ]:
import numpy as np
arr = np.arange(1,10).reshape(3,3)
# print(arr)

# np.diag(array, shift)
arr2 = np.diag(arr, k=0)
# print(arr2)

arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Matrix Slicing

In [ ]:
import numpy as np
arr = np.array([
    [5,6,7,8],
    [1,2,3,4],
])
lst = []
for i in np.nditer(arr):
    lst.append(i)
# print(np.array(lst))

lst1=[]
for i in arr:
    for j in i:
        lst1.append(j)
# print(np.array(lst))

arr1 = np.arange(10,100,5).reshape(3,6)
print(arr1)
print('------------------')
reshaped_arr1 = arr1[:2]
print(reshaped_arr1)
print('------------------')
reshaped_arr2 = arr1[:,1:4]
print(reshaped_arr2)
print('------------------')
# reshaped_arr3 = arr1[row start:row end,col start:col end]
reshaped_arr3 = arr1[1:2,1:4]
print(reshaped_arr3)

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
------------------
[[10 15 20 25 30 35]
 [40 45 50 55 60 65]]
------------------
[[15 20 25]
 [45 50 55]
 [75 80 85]]
------------------
[[45 50 55]]


nditer(),advanced-indexing,copy

reshape, flatten, ravel(arr, order="F"|"C"), concatenate((ar1,ar2),axis=0|1), tranpose - arr.T, array_split, split, mathmatical functions, sorting, searching, counting, 